
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/lib/supabase';

const SUPABASE_URL = "https://wdfoznswlscixgfersin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkZm96bnN3bHNjaXhnZmVyc2luIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NTUwNjQsImV4cCI6MjA2MDUzMTA2NH0.3zXTcgCiS-Si_t72w2YMu6RBtS4xsvP2Fix0tof79NQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
